### ISSUE TITLE
How to send the output to the stable diffusion webui (AUTOMATIC 1111 webui)

### ISSUE THREAD

**Issue by AllenEdgarPoe** [jordip/prompt-generator-api#1]
Your work is amazing. I've got impressed by the speed especially, and I want to use this repo rather than other prompt builder. 
Can you guide me how to send the generated prompt to the webui? Currently I'm using the automatic 1111 webui.
Specifically, I'd like to send the generated output to the webui's prompt. 
Any suggestions? 

![image](https://user-images.githubusercontent.com/43398106/214744502-9f6e2573-d9e6-4b19-b2e1-38f79042a9be.png)

**Comment by jordip** [comment]
Hello,

Thanks for your review. Please have a look at https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator

Both projects use the same underlying model to generate the prompts.

Best regards
