### ISSUE TITLE
Does't work

### ISSUE THREAD

**Issue by MMACoach** [jordip/prompt-generator-api#2]
Hi

Then I do this curl http://127.0.0.1:5000/generate -H "Content-Type: application/json" -d '"prompt":"cat with sunglasses"' -X POST
Response "message": "The browser (or proxy) sent a request that this server could not understand."}

On server response 127.0.0.1 - - [25/Apr/2023 06:45:33] "POST /generate HTTP/1.1" 400 -

Could you help me?

**Comment by jordip** [comment]
Hi there,

Your payload is wrong, fix the -d argument.

https://linuxize.com/post/curl-post-request/#specifying-the-content-type

**Comment by MMACoach** [comment]
Hi

Sorry, but I am not a great user of pyton.
In example you givu this request

curl http://127.0.0.1:5000/generate -H "Content-Type: application/json" '{"prompt":"cat with sunglasses"}' -X POST

How I can modifed thit? that it works?
